### PR TITLE
Interrogate

### PR DESCRIPTION
**Pull request by jexio**
**Description of changes**

[interrogate](https://interrogate.readthedocs.io/en/latest/)
I've added a new task to check the coverage of docstrings

### CODE REVIEW

**Comment by pawamoy** [comment]
Whewhew, nice! Let me review this :slightly_smiling_face:

**Review by pawamoy — APPROVED** [review]
That's fantastic, thank you so much!

Just a nitpick and a suggestion for the docstring, otherwise LGTM!

**Comment by jexio** [comment]
@pawamoy Hi, I think I fixed what you asked for :slightly_smiling_face:

**Comment by pawamoy** [comment]
Perfect, thanks a lot!

**Comment by pawamoy** [comment]
Released in v0.9.0 :slightly_smiling_face:

**Pull request merged**
